version: "2.4"

services:
  security:
    build: ./app
    ports:
     - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./app/api:/app/api
  db:
    build: ./database-service
    ports: 
     - "33060:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
